version: 2
general:
  branches:
    only:
      - master
jobs:
  compile:
    docker:
      - image: redkoibox/microhelix-compile
    steps:
      - checkout
      - run:
          name: Compile Micro~Helix
          command: ./build-linux.sh
      - persist_to_workspace:
          root: compiled
          paths: microhelix.tar.gz
workflows:
  version: 2
  compile_and_push:
    jobs:
      - compile
